name:                aoc
version:             0.1.0.0
github:              "peri4n/haskell-challenges"
license:             BSD3
author:              "Fabian Bull"
maintainer:          "spam+aoc@fbull.de"
copyright:           "2022 Fabian Bull"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Collection of christmas puzzles

dependencies:
- base >= 4.7 && < 5
- containers
- unordered-containers
- split
- regex-applicative
- megaparsec
- text

library:
  source-dirs: src

default-extensions:
- OverloadedStrings

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
    - HUnit
