name:                haskell-euler
version:             0.1.0.0
github:              "peri4n/haskell-euler"
license:             BSD3
author:              "Fabian Bull"
maintainer:          "bull.fabian@googlemail.com"
copyright:           "GPG"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Project Euler solutions
category:            code-challenge

description:         Please see the README on GitHub at <https://github.com/peri4n/haskell-euler#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  euler-exe:
    main:                Main.hs
    other-modules:       []
    source-dirs:         app
    dependencies:
    - haskell-euler
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N

tests:
  haskell-euler-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - haskell-euler
    - HUnit
